apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: notino-demo
spec:
  interval: "3m"
  subscriptions:
    - image:
        repoURL: ghcr.io/vojtechmares-examples/guestbook
        imageSelectionStrategy: SemVer
        allowTags: ^v?[0-9]+\.[0-9]+\.[0-9]+([\+-].*)?$
        strictSemvers: false
    - git:
        repoURL: https://github.com/vojtechmares-examples/notino-kargo.git
        branch: main
        strictSemvers: false
