apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/vojtechmares-exaples/notino-kargo.git
        revision: HEAD
        directories:
          - path: env/*
  template:
    metadata:
      name: guestbook-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: notino-demo:{{path.basename}}
    spec:
      destination:
        namespace: guestbook-{{path.basename}}
        server: "https://kubernetes.default.svc"
      project: guestbook
      source:
        path: ./
        repoURL: https://github.com/vojtechmares-exaples/notino-kargo.git
        targetRevision: env/{{path.basename}}
